apiVersion: v1
kind: Service
metadata:
  name: snowflake-id-generator-service
  namespace: default
spec:
  selector:
    app: snowflake-id-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
